version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "8080:5050"
    volumes:
      - ./backend/src:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27018
    volumes:
      - ./data:/data/db
    restart: always
